#!/usr/bin/env bash
# Script to install and configure HAProxy as a load balancer

apt-get -y install software-properties-common

add-apt-repository -y ppa:vbernat/haproxy-2.0

apt-get -y update

apt-get -y install haproxy=2.0.*

# Configure HAProxy
cat <<EOF > /etc/haproxy/haproxy.cfg
frontend http
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    server 475557-web-01 34.204.81.89:80 check
    server 475557-web-02 18.214.88.65:80 check
EOF

# Restart HAProxy service
service haproxy restart

