#!/bin/bash

# Name of the private key
private_key="school"

# Number of bits in the key
key_bits=4096

# Passphrase to protect the key
passphrase="betty"

# Generate the key pair
ssh-keygen -t rsa -b $key_bits -f $private_key -N $passphrase

echo "RSA key pair generated."
