#!/usr/bin/env bash

# Current working directory
DIR=$(pwd)

# Create an RSA key pair
ssh-keygen -t rsa -b 4096 -f "$DIR/school" -N "betty" >/dev/null 2>&1

# Check if the private key is created
if [ -f "$DIR/school" ]; then
    if ssh-keygen -y -f "$DIR/school" >/dev/null 2>&1; then
        echo "school: OpenSSH private key"
    else
        echo "Error: Failed to verify the private key type."
    fi
else
    echo "Error: Failed to generate the key pair."
fi
